name: flash-sale-dev

services:
  postgres:
    image: postgres:16-alpine
    container_name: flash-sale-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flash_sale_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - flash-sale-network

  redis:
    image: redis:7-alpine
    container_name: flash-sale-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - flash-sale-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  flash-sale-network:
    driver: bridge